name: CI

on:
  push:
    paths: '**'

jobs:
  push_x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Create empty settings.env file
        run: touch settings.env
      - name: Build containers
        run: make build
      - name: Push containers
        run: make push

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Run pytest
        run: make test
