name: ci

on:
  push:
    branches: "*"

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create empty settings.env file
        run: touch settings.env
      - name: Build containers
        run: make build
      - name: Push containers
        run: make push
